# Generated by Django 4.0.3 on 2022-03-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_order', models.TextField()),
                ('department', models.PositiveSmallIntegerField(choices=[(1, 'Уборка'), (2, 'Связь, Интернет'), (3, 'Отопление, Вода, Туалет'), (4, 'Электрика'), (5, 'Ремонт помещения'), (6, 'Документы, Договора, Счета')], default=6)),
                ('status', models.CharField(choices=[('не принято', 'Ожидает рассмотрения'), ('принято', 'Рассматривается'), ('в работе', 'Принято к исполнению'), ('выполнено', 'Выполенно')], default='не принято', max_length=32)),
                ('date_added', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
