# Generated by Django 4.0.3 on 2022-03-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0003_order_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_document', models.DateTimeField(blank=True, default=None, null=True)),
                ('number_invoice', models.CharField(max_length=10)),
                ('number_document', models.CharField(max_length=10)),
                ('client', models.CharField(max_length=100)),
                ('inn', models.CharField(max_length=12)),
                ('kpp', models.CharField(blank=True, max_length=12, null=True)),
                ('adres', models.CharField(max_length=100)),
                ('telephon', models.CharField(blank=True, max_length=12, null=True)),
                ('service', models.CharField(max_length=150)),
                ('cost', models.CharField(max_length=11)),
                ('month', models.CharField(choices=[('январь', 'январь'), ('февраль', 'февраль'), ('март', 'март'), ('апрель', 'апрель'), ('май', 'май'), ('июнь', 'июнь'), ('июль', 'июль'), ('август', 'август'), ('сентябрь', 'сентябрь'), ('октябрь', 'октябрь'), ('ноябрь', 'ноябрь'), ('декабрь', 'декабрь')], default='январь', max_length=9)),
            ],
        ),
    ]
